---
# defaults file for configure_sso_openid
configure_sso_openid_app_version_map: {}
configure_sso_openid_temp_pw_file: {}
configure_sso_openid_install_apps: []
configure_sso_openid_basedn: ""
configure_sso_openid_signing_method: "RS256"
configure_sso_openid_external_hostname: ""
configure_sso_openid_clients:
  nextcloud:
    name: "nextcloud"
    clientid: "nextcloud"
    clientsecret: "notverysafe"
  ox:
    name: "open-xchange"
    clientid: "open-xchange"
    clientsecret: "notverysafe"
