---
# defaults file for install_multitenant_acls
install_multitenant_acls_customer_name: ""
install_multitenant_acls_multitenant_acls: []
install_multitenant_acls_json_path: ""
install_multitenant_acls_package_name: ""
install_multitenant_acls_script_name: ""
install_multitenant_acls_keycloak_base: ""
install_multitenant_acls_hide_logging: true
install_multitenant_acls_server_type: "master"
install_multitenant_acls_customer_repo_name: ""
install_multitenant_acls_customer_repo_parts: ""
install_multitenant_acls_customer_repo_username: ""
install_multitenant_acls_customer_repo_server: ""
install_multitenant_acls_customer_repo_password: ""
install_multitenant_acls_customer_repo_prefix: "apt/{{ install_multitenant_acls_customer_repo_username }}"
