---
# defaults file for configure_license

configure_license_validity: ""
configure_license_shop_password: ""
configure_license_shop_id: ""
configure_license_shop_username: ""
configure_license_max_users: ""
configure_license_basedn: ""
configure_license_type: "server_license"
configure_license_file: false
configure_license_server_type: "master"