---
# defaults file for install_lets_encrypt
install_lets_encrypt_use_letsencrypt_staging: false
install_lets_encrypt_implement_ugly_letsencrypt_workaround: false
install_lets_encrypt_temp_pw_file: {}
install_lets_encrypt_temp_dir: {}
install_lets_encrypt_service_version_map: {}
install_lets_encrypt_service_name_list: {}
install_lets_encrypt_force_package_upgrade: false
install_lets_encrypt_external_hostname: ""