---
# defaults file for cleanup_portal
cleanup_portal_basedn: ""
cleanup_portal_install_services: []
cleanup_portal_domain_admin_group: "cn=Domain Admins,cn=groups,{{ cleanup_portal_basedn }}"
cleanup_portal_portal_dn: "cn=portals,cn=univention,{{ cleanup_portal_basedn }}"
cleanup_portal_prometheus_dn: 'cn=prometheus,cn=entry,{{ cleanup_portal_portal_dn }}'
cleanup_portal_admin_dashboard_dn: 'cn=admin-dashboard,cn=entry,{{ cleanup_portal_portal_dn }}'