---
# defaults file for portal_entry
portal_entry_base_dn: ""
portal_entry_portal_dn: "cn=portals,cn=univention,{{ portal_entry_base_dn }}"
portal_entry_entries: []
portal_entry_install_list: []
portal_entry_drift_detection: true
portal_entry_remove_unscoped: false
