---
# defaults file for configure_keycloak_client

configure_keycloak_client_oidc_broker_secret: ""
configure_keycloak_client_keycloak_password: ""
configure_keycloak_client_basedn: ""
configure_keycloak_client_keycloak_server_id: ""
configure_keycloak_client_keycloak_server: ""
configure_keycloak_client_config_type: "dynamic"
configure_keycloak_client_hostname: "{{ inventory_hostname }}"
