---
# defaults file for umc_policies_maintenance
umc_policies_maintenance_basedn: ""
umc_policies_maintenance_patchhour: "5"
umc_policies_maintenance_patchminute: "00"
umc_policies_maintenance_patchday: "Tuesday"
umc_policies_maintenance_release_verion: ""
umc_policies_maintenance_hostname: "{{ inventory_hostname }}"
umc_policies_maintenance_autoupdate_enabled: true
