---
# handlers file for configure_office_suite

- name: "Restart collabora-online"
  ansible.builtin.shell: "univention-app stop collabora-online; univention-app start collabora-online"
  tags:
    - "configure_office_suite"
    - "configure_office_suite_restart_collabora"
