---
# defaults file for ldapsearch_user

ldapsearch_user_basedn: ""
ldapsearch_user_list: []
ldapsearch_user_list_tenantbased: []
ldapsearch_user_server_type: "master"
ldapsearch_user_hide_logging: true
