---
# handlers file for install_apps_ox_post

- name: "Restart dovecot"
  ansible.builtin.service:
    name: "dovecot"
    state: "restarted"

- name: "Restart OpenXchange"
  ansible.builtin.service:
    name: "open-xchange"
    state: "restarted"
