---
# defaults file for configure_office_suite

configure_office_suite_office_suite: "collabora-online"
configure_office_suite_supported_office_suites:
  - onlyoffice
  - collabora-online
configure_office_suite_onlyoffice_formats:
  csv: "false"
  doc: "false"
  docm: "false"
  docx: "true"
  dotx: "false"
  epub: "false"
  html: "false"
  odp: "true"
  ods: "true"
  odt: "true"
  otp: "false"
  ots: "false"
  ott: "false"
  pdf: "false"
  potm: "false"
  potx: "false"
  ppsm: "false"
  ppsx: "false"
  ppt: "false"
  pptm: "false"
  pptx: "true"
  rtf: "false"
  txt: "false"
  xls: "false"
  xlsm: "false"
  xlsx: "true"
  xltm: "false"
  xltx: "false"
configure_office_suite_collabora_license_key: ""
configure_office_suite_app_version_map: {}
configure_office_suite_temp_pw_file: ""
configure_office_suite_install_apps: []
