---
# defaults file for configure_apps_postfix_relay
configure_apps_postfix_relay_enabled: false
configure_apps_postfix_relay_host: ""
configure_apps_postfix_relay_port: 25
configure_apps_postfix_relay_username: ""
configure_apps_postfix_relay_password: ""
configure_apps_postfix_relay_hide_logging: true
